dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: h7jAz4hztwJkCppBctHp0rWXGcODUSKB8BUU60/PAsYjoU46y6GTxDQyi98csFmBGqofbT2jfip0QlZSXp/ffpcVyw72TwT66GzgEjTpdsL0WuC4E4ixufgez0QOo6G4Yw5AMrlJrIU8u1dpO8JA/t/IPYSYJj3JlrMer7d9EyWd1EjH66EUcvImixTtCr7YCnsb4FaoiwG72OeXAgDFWbYos4npdxQ9oCxwybJEI4hBIMNn0pMPl8uAZBOfC0nRJB0H9gD9YILCNqVU1eLeg+AhBIcRCrHn3f/IFCHtL5dVpD3tZ5KdJEdiwsJXpUyEMS67dwdX1xN8gTOUUDCs3VvRBdCCNdpi8VfGNx7VaNDu8VYr+0xKputiqBUBEHAtW9osimiPOwy+L5AVTfCm9Zawa0bqE4BQZoXsunv/4rOsEL+NE/hy+VFPpEq1F10d0hMh1ybQ91r3yWiyhyJYi1+7lM6TFeyunOm46+xQVZTS7uOPUbM7oQA1hVHvLQv7SGk4XVw/6oUID2mcy5aeHix3tAvNm80TLokBJJiv/IblDnGRDMcpkaVTBpYL/DUOtfgjjbHgys7zdia6vdw/ZRjLCehEmFzWtZ0NMwjSHjyhklCu88JsAjsoj3y86bCWlSr2Aot4wS0oMsSheoVKeT/vZCHZ7fO/9TVEgGEIB6I=
