---
- name: Update cache
  apt:
    update_cache: true
  tags: ruby

- name: Install Ruby and Bundler
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ruby-full
    - ruby-bundler
    - build-essential
  tags: ruby
